# fly.toml app configuration file generated for hm-market-server on 2023-10-30T19:29:49+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hm-market-server"
primary_region = "hkg"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
